create-example-config:
	echo '{' > config.json && \
	echo '  "calibration_data_path": "",' >> config.json && \
	echo '  "arm_kinematics_path": "",' >> config.json && \
	echo '  "arm_frame_ox": ,' >> config.json && \
	echo '  "arm_frame_oy": ,' >> config.json && \
	echo '  "arm_frame_oz": ,' >> config.json && \
	echo '  "arm_frame_theta": ' >> config.json && \
	echo '}' >> config.json
